= Añadir actividad manual
:allow-uri-read: 




=== Añadir actividad manual

Para que una secuencia de comandos del repositorio realice cualquier acción, se debe crear una actividad que asocie dicha secuencia de comandos a un desencadenador seleccionado. En este ejemplo, se ejecuta cuando el administrador de VDS activa manualmente el script.

Los eventos con secuencias de comandos VDS ofrecen muchos otros tipos de desencadenadores de actividad, como _Create Server_, que pueden utilizarse como alternativa al tipo de evento _Manual_. El uso de _Create Server_ simplemente ejecutaría este script en todas las máquinas virtuales recién creadas en VDS. _Create Server_ y otros desencadenadores se documentan y se pueden explorar link:Management.Scripted_Events.scripted_events.html["aquí"].

.Para crear una actividad y vincular esta secuencia de comandos a una acción:
. Desplácese a la sección Eventos de secuencia de comandos de VDS
. En _Activities_ haga clic en _+ Agregar actividad_
. En la ventana de diálogo abierta, introduzca la siguiente información:
+
** *Nombre:* asigne un nombre a esta actividad
** *Descripción:* opcionalmente, introduzca una descripción
** *Despliegue* Seleccione la implementación deseada en la lista desplegable
** *Script:* Seleccione la secuencia de comandos de instalación (o desinstalación) de la lista desplegable. Podría ser el guión global o el script de cliente que ha clonado y personalizado.
** *Argumentos:* dejar en blanco
** *Casilla de verificación activada:* `Check` la caja
** *Tipo de evento:* Seleccione `Manual` de la lista desplegable
** *Tipo de destino:* Seleccione `Servers` botón de radio
** *Servidores administrados:* `Check` La caja para cada equipo virtual que debería recibir esta desinstalación.



