= Añadir actividad de instalación y desinstalación de la aplicación
:allow-uri-read: 




=== Añadir actividad de instalación y desinstalación de la aplicación

Para que una secuencia de comandos del repositorio realice cualquier acción, se debe crear una actividad que asocie dicha secuencia de comandos a un desencadenador seleccionado. En este ejemplo, la actividad instalará o desinstalará esta aplicación cuando se agregue o elimine la aplicación del área de trabajo (desde la página _Workspace > Applications_ de VDS).

Los eventos con secuencias de comandos VDS ofrecen muchos otros tipos de desencadenadores de actividad, como _Create Server_, que se pueden utilizar como alternativa al tipo de evento _Application Install_ (o _Application Uninstall_). El uso de _Create Server_ simplemente ejecutaría esta instalación de la aplicación en todas las máquinas virtuales recién creadas en VDS. _Create Server_ y otros desencadenadores se documentan y se pueden explorar link:Management.Scripted_Events.scripted_events.html["aquí"].


NOTE: Esta aplicación deberá estar presente en la biblioteca de aplicaciones VDS. Este link:Management.Applications.application_entitlement_workflow.html#add-applications-to-the-app-catalog["sección"] Del derecho a la aplicación para el artículo de RDS trata la adición de aplicaciones a la biblioteca.

.Para crear una actividad y vincular este script a una acción:
. Desplácese a la sección _script Events_ de VDS
. En _Activities_ haga clic en _+ Agregar actividad_
. En la ventana de diálogo abierta, introduzca la siguiente información:
+
** *Nombre:* asigne un nombre a esta actividad
** *Descripción:* opcionalmente, introduzca una descripción
** *Despliegue* Seleccione la implementación deseada en la lista desplegable
** *Script:* Seleccione la secuencia de comandos de instalación (o desinstalación) de la lista desplegable. Podría ser el guión global o el script de cliente que ha clonado y personalizado.
** *Argumentos:* dejar en blanco
** *Casilla de verificación activada:* `Check` la caja
** *Tipo de evento:* Seleccione `Application Install` (O desinstalación de aplicaciones) en la lista desplegable
** *Aplicación:* Seleccione esta aplicación en la lista desplegable
** *Ruta de acceso directo:* Introduzca la ruta de acceso directo predeterminada para esta aplicación (indicada anteriormente)



